[package]
name = "proinit"
version = "0.1.0"
authors = ["RisuSofos <risusofos@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
structopt = "0.3.21"
